import { Product, Collection } from "./types";

export const PRODUCTS: Product[] = [
  {
    id: "1",
    slug: "esp-wroom-32",
    name: "ESP32 WROOM WiFi Module | USB Type-C (38 PIN)",
    regularPrice: 499,
    salePrice: 425,
    discount: 14,
    inStock: true,
    collection: "ESP Modules",
    image: "https://majestronicz.in/cdn/shop/files/esp-38-1.webp",
    tags: ["WiFi", "ESP32", "38-Pin", "USB-C", "IoT"],
    description: "The ESP32 WROOM WiFi Module with USB Type-C connector and 38 GPIO pins. Dual-core Xtensa LX6 processor running at up to 240MHz. Integrated 2.4 GHz Wi-Fi and Bluetooth 4.2. Perfect for IoT applications with built-in USB-C for easy programming.",
    sku: "ESP-WROOM-32-38-C",
    rating: 4.8,
    reviewCount: 124,
  },
  {
    id: "2",
    slug: "esp32-wroom-30-pin",
    name: "ESP32 WROOM Wi-Fi Module (30 Pins)",
    regularPrice: 425,
    salePrice: 375,
    discount: 12,
    inStock: false,
    collection: "ESP Modules",
    image: "https://majestronicz.in/cdn/shop/files/WROOMBTYPE.webp",
    tags: ["WiFi", "ESP32", "30-Pin"],
    description: "Compact ESP32 WROOM development board with 30 GPIO pins. Features dual-core processor, integrated WiFi and Bluetooth. Ideal for breadboard prototyping.",
    sku: "ESP-WROOM-30",
    rating: 4.6,
    reviewCount: 89,
  },
  {
    id: "3",
    slug: "esp8266-ch340",
    name: "ESP8266 CH340 V3 WiFi Development Board",
    regularPrice: 250,
    salePrice: 250,
    discount: 0,
    inStock: true,
    collection: "ESP Modules",
    image: "https://majestronicz.in/cdn/shop/files/ch340-3.jpg",
    tags: ["WiFi", "ESP8266", "CH340", "Breadboard", "IoT"],
    description: "ESP8266 development board with CH340 USB-to-serial chip. NodeMCU compatible firmware. 11 digital GPIO pins, 1 analog input. Auto-reset circuit for easy programming.",
    sku: "ESP8266-CH340-V3",
    rating: 4.5,
    reviewCount: 203,
  },
  {
    id: "4",
    slug: "esp32-camera-ov2640",
    name: "ESP32 Camera Module (OV2640)",
    regularPrice: 765,
    salePrice: 599,
    discount: 21,
    inStock: true,
    collection: "ESP Modules",
    image: "https://majestronicz.in/cdn/shop/files/ESPFRONT-1.jpg",
    tags: ["Camera", "ESP32", "OV2640", "Vision", "AI"],
    description: "ESP32-CAM module with OV2640 2MP camera sensor. Supports image WiFi upload, take photo, and video stream. Built-in TF card slot for data storage. Perfect for AI vision projects.",
    sku: "ESP32-CAM-OV2640",
    rating: 4.7,
    reviewCount: 156,
  },
  {
    id: "5",
    slug: "esp32-cp2102",
    name: "ESP8266 CP2102",
    regularPrice: 450,
    salePrice: 280,
    discount: 37,
    inStock: true,
    collection: "ESP Modules",
    image: "https://majestronicz.in/cdn/shop/files/8266.avif",
    tags: ["ESP8266", "CP2102", "WiFi"],
    description: "ESP8266 module with reliable CP2102 USB-to-UART bridge. Stable connection and easy driver support on all OS. Great for projects requiring consistent serial communication.",
    sku: "ESP8266-CP2102",
    rating: 4.4,
    reviewCount: 67,
  },
  {
    id: "6",
    slug: "esp32-cam-base-board",
    name: "ESP32 Cam Base Board",
    regularPrice: 180,
    salePrice: 140,
    discount: 22,
    inStock: true,
    collection: "ESP Modules",
    image: "https://majestronicz.in/cdn/shop/files/cam-1.jpg",
    tags: ["ESP32", "Camera", "Base Board"],
    description: "Dedicated base board for ESP32-CAM module. Features USB-C power input, built-in programmer (no external FTDI needed), reset button, and status LED.",
    sku: "ESP32-CAM-BASE",
    rating: 4.6,
    reviewCount: 45,
  },
  {
    id: "7",
    slug: "esp32-c3-supermini",
    name: "ESP32-C3 SuperMini IoT Board WiFi & Bluetooth 5.0",
    regularPrice: 499,
    salePrice: 275,
    discount: 44,
    inStock: true,
    collection: "ESP Modules",
    image: "https://majestronicz.in/cdn/shop/files/c3-supermini-1.jpg",
    tags: ["ESP32-C3", "BLE", "WiFi", "Compact", "IoT"],
    description: "Ultra-compact ESP32-C3 SuperMini board. RISC-V single core processor at 160MHz, 2.4GHz WiFi and Bluetooth 5.0 BLE. 400KB SRAM, 4MB Flash. Smallest ESP32 form factor.",
    sku: "ESP32-C3-SUPERMINI",
    rating: 4.9,
    reviewCount: 212,
  },
  {
    id: "8",
    slug: "esp32-30-pin-expansion-board",
    name: "ESP32 - 30 Pin Expansion Board",
    regularPrice: 150,
    salePrice: 125,
    discount: 16,
    inStock: false,
    collection: "ESP Modules",
    image: "https://majestronicz.in/cdn/shop/files/30pinexp.jpg",
    tags: ["ESP32", "Expansion", "GPIO", "30-Pin"],
    description: "Expansion board for ESP32 30-pin modules. Breaks out all GPIO pins with 3.3V/5V/GND rails. Perfect for breadboard-free prototyping.",
    sku: "ESP32-EXP-30",
    rating: 4.3,
    reviewCount: 38,
  },
  {
    id: "9",
    slug: "esp32-wroom-38-pins",
    name: "ESP32 WROOM Wi-Fi Module (38 Pins)",
    regularPrice: 410,
    salePrice: 375,
    discount: 8,
    inStock: true,
    collection: "ESP Modules",
    image: "https://majestronicz.in/cdn/shop/files/esp32-1_886ca99a.jpg",
    tags: ["WiFi", "ESP32", "38-Pin"],
    description: "Classic ESP32 WROOM development board with 38 GPIO pins. Proven design with broad community support. Dual-core 240MHz CPU, 4MB Flash, 520KB SRAM.",
    sku: "ESP-WROOM-38",
    rating: 4.7,
    reviewCount: 189,
  },
  {
    id: "10",
    slug: "esp32-38-pin-expansion-typec",
    name: "ESP32 38-Pin Expansion Board with Type-C",
    regularPrice: 159,
    salePrice: 159,
    discount: 0,
    inStock: false,
    collection: "ESP Modules",
    image: "https://majestronicz.in/cdn/shop/files/expansion-2.jpg",
    tags: ["ESP32", "Expansion", "Type-C", "GPIO"],
    description: "Premium expansion board for ESP32 38-pin modules with USB Type-C power input. All GPIO exposed with labeled pin headers.",
    sku: "ESP32-EXP-38-C",
    rating: 4.5,
    reviewCount: 29,
  },
  {
    id: "11",
    slug: "esp-01-wi-fi-module",
    name: "ESP01 Wi-Fi Module",
    regularPrice: 129,
    salePrice: 129,
    discount: 0,
    inStock: true,
    collection: "ESP Modules",
    image: "https://majestronicz.in/cdn/shop/files/download_4.jpg",
    tags: ["ESP8266", "ESP-01", "Compact", "WiFi"],
    description: "The original ESP-01 WiFi module. Smallest ESP8266 form factor. 1MB Flash, 2 GPIO pins. Ideal for adding WiFi to microcontroller projects via AT commands.",
    sku: "ESP-01",
    rating: 4.2,
    reviewCount: 334,
  },
  {
    id: "12",
    slug: "esp8266-d1-mini-v2",
    name: "ESP8266 D1 Mini V2 - NodeMcu 4M Lua WiFi IoT Board",
    regularPrice: 220,
    salePrice: 199,
    discount: 9,
    inStock: true,
    collection: "ESP Modules",
    image: "https://majestronicz.in/cdn/shop/files/D1.webp",
    tags: ["ESP8266", "D1 Mini", "NodeMCU", "Lua", "IoT"],
    description: "D1 Mini form factor ESP8266 board with 4MB flash. Compatible with Arduino IDE and MicroPython. 11 digital GPIO, 1 analog. Perfect for compact IoT builds.",
    sku: "ESP8266-D1-MINI-V2",
    rating: 4.8,
    reviewCount: 267,
  },
  // General catalog
  {
    id: "13",
    slug: "hc-sr04-ultrasonic",
    name: "HC-SR04 Ultrasonic Distance Sensor",
    regularPrice: 89,
    salePrice: 79,
    discount: 11,
    inStock: true,
    collection: "Sensors",
    image: "https://majestronicz.in/cdn/shop/files/hcsr04.jpg",
    tags: ["Sensor", "Ultrasonic", "Distance", "Arduino"],
    description: "HC-SR04 ultrasonic sensor for distance measurement from 2cm to 400cm. 3mm accuracy, 15° measuring angle. Compatible with Arduino, ESP32, and Raspberry Pi.",
    sku: "HC-SR04",
    rating: 4.6,
    reviewCount: 512,
  },
  {
    id: "14",
    slug: "arduino-uno-smd",
    name: "Arduino UNO SMD R3 Development Board",
    regularPrice: 339,
    salePrice: 249,
    discount: 26,
    inStock: true,
    collection: "Arduino",
    image: "https://majestronicz.in/cdn/shop/files/arduino-uno.jpg",
    tags: ["Arduino", "UNO", "SMD", "ATmega328P"],
    description: "Arduino UNO SMD R3 with surface-mount ATmega328P. 14 digital I/O pins, 6 analog inputs, 16MHz crystal. Compatible with all standard Arduino shields.",
    sku: "ARD-UNO-SMD",
    rating: 4.9,
    reviewCount: 891,
  },
  {
    id: "15",
    slug: "sg90-servo-motor",
    name: "SG-90 Micro Servo Motor 9g",
    regularPrice: 98,
    salePrice: 98,
    discount: 0,
    inStock: true,
    collection: "Motors & Actuators",
    image: "https://majestronicz.in/cdn/shop/files/sg90.jpg",
    tags: ["Servo", "Motor", "SG90", "Robotics", "RC"],
    description: "SG-90 9g micro servo with 180° rotation range. 1.8kg/cm torque at 4.8V. Includes mounting hardware and 3 servo horns. Perfect for robotic arms and RC projects.",
    sku: "SG90-SERVO",
    rating: 4.5,
    reviewCount: 445,
  },
  {
    id: "16",
    slug: "oled-096-white",
    name: "0.96 Inch OLED Display White (128x64 I2C)",
    regularPrice: 230,
    salePrice: 209,
    discount: 9,
    inStock: true,
    collection: "Displays & Screens",
    image: "https://majestronicz.in/cdn/shop/files/oled096.jpg",
    tags: ["OLED", "Display", "I2C", "SSD1306", "0.96 inch"],
    description: "128x64 pixel 0.96-inch white OLED display with I2C interface. SSD1306 driver. Works at 3.3V and 5V. Wide viewing angle, self-luminous, no backlight needed.",
    sku: "OLED-096-WHT",
    rating: 4.7,
    reviewCount: 678,
  },
  {
    id: "17",
    slug: "relay-1ch-5v",
    name: "1 Channel 5V Relay Module",
    regularPrice: 45,
    salePrice: 45,
    discount: 0,
    inStock: true,
    collection: "Relay Modules",
    image: "https://majestronicz.in/cdn/shop/files/relay1ch.jpg",
    tags: ["Relay", "5V", "Module", "AC Control"],
    description: "Single channel 5V relay module with optocoupler isolation. Controls AC loads up to 250V/10A or DC 30V/10A. Active low trigger. LED indicator for relay state.",
    sku: "RELAY-1CH-5V",
    rating: 4.4,
    reviewCount: 923,
  },
];

export const COLLECTIONS: Collection[] = [
  { slug: "esp-modules",        name: "ESP Modules",          description: "WiFi & Bluetooth IoT modules — ESP32, ESP8266, ESP-CAM and more",  image: "https://majestronicz.in/cdn/shop/files/esp-38-1.webp", productCount: 12, icon: "📡" },
  { slug: "arduino",            name: "Arduino",              description: "Official and compatible Arduino boards for every project",         image: "https://majestronicz.in/cdn/shop/files/arduino-uno.jpg", productCount: 8, icon: "🔵" },
  { slug: "soldering",          name: "Soldering",            description: "Soldering irons, flux, solder wire, desoldering tools",           image: "https://majestronicz.in/cdn/shop/files/solder.jpg", productCount: 15, icon: "🔧" },
  { slug: "sensors",            name: "Sensors",              description: "Temperature, humidity, motion, distance, light and more sensors",  image: "https://majestronicz.in/cdn/shop/files/hcsr04.jpg", productCount: 24, icon: "🌡️" },
  { slug: "displays-screens",   name: "Displays & Screens",   description: "OLED, TFT, LCD displays and screen modules",                      image: "https://majestronicz.in/cdn/shop/files/oled096.jpg", productCount: 11, icon: "🖥️" },
  { slug: "relay-modules",      name: "Relay Modules",        description: "1, 2, 4 and 8 channel relay boards for load switching",           image: "https://majestronicz.in/cdn/shop/files/relay1ch.jpg", productCount: 7, icon: "⚡" },
  { slug: "motors-actuators",   name: "Motors & Actuators",   description: "Servo, stepper, DC motors and actuators",                         image: "https://majestronicz.in/cdn/shop/files/sg90.jpg", productCount: 18, icon: "⚙️" },
  { slug: "passive-components", name: "Passive Components",   description: "Resistors, capacitors, LEDs, diodes and more",                    image: "https://majestronicz.in/cdn/shop/files/passive.jpg", productCount: 50, icon: "🔌" },
  { slug: "wires-connectors",   name: "Wires & Connectors",   description: "Jumper wires, ribbon cables, connectors and pin headers",         image: "https://majestronicz.in/cdn/shop/files/wires.jpg", productCount: 22, icon: "🔗" },
  { slug: "power-supply",       name: "Power Supply",         description: "Voltage regulators, LiPo batteries, power modules and chargers",  image: "https://majestronicz.in/cdn/shop/files/power.jpg", productCount: 14, icon: "🔋" },
];

export function getProductsByCollection(collectionName: string): Product[] {
  const col = COLLECTIONS.find(c => c.slug === collectionName);
  if (!col) return [];
  return PRODUCTS.filter(p => p.collection === col.name);
}

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find(p => p.slug === slug);
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return PRODUCTS
    .filter(p => p.slug !== product.slug && p.collection === product.collection)
    .slice(0, limit);
}

export const COLLECTION_SLUG_MAP: Record<string, string> = {
  "esp-modules": "ESP Modules",
  "arduino": "Arduino",
  "soldering": "Soldering",
  "sensors": "Sensors",
  "displays-screens": "Displays & Screens",
  "relay-modules": "Relay Modules",
  "motors-actuators": "Motors & Actuators",
  "passive-components": "Passive Components",
  "wires-connectors": "Wires & Connectors",
  "power-supply": "Power Supply",
};
