#!/usr/bin/env node
/**
 * Merge tenant branding into .env.local (keeps secrets from existing .env / .env.local).
 * Usage: node scripts/switch-tenant.mjs trustnest
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");
const tenantsDir = path.join(root, "env", "tenants");

function parseEnv(content) {
  const obj = {};
  if (!content) return obj;
  for (const line of content.split(/\r?\n/)) {
    const t = line.trim();
    if (!t || t.startsWith("#")) continue;
    const i = t.indexOf("=");
    if (i === -1) continue;
    const key = t.slice(0, i).trim();
    let val = t.slice(i + 1).trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    obj[key] = val;
  }
  return obj;
}

function stringifyEnv(obj, header) {
  const lines = [header, ""];
  for (const [k, v] of Object.entries(obj).sort(([a], [b]) => a.localeCompare(b))) {
    const needsQuotes = /[\s#]/.test(v);
    lines.push(`${k}=${needsQuotes ? `"${v.replace(/"/g, '\\"')}"` : v}`);
  }
  lines.push("");
  return lines.join("\n");
}

const SECRET_KEYS = new Set([
  "DATABASE_URL",
  "NEXTAUTH_SECRET",
  "GOOGLE_CLIENT_ID",
  "GOOGLE_CLIENT_SECRET",
  "OPENAI_API_KEY",
  "AWS_ACCESS_KEY_ID",
  "AWS_SECRET_ACCESS_KEY",
  "AWS_S3_BUCKET_NAME",
  "TELEGRAM_BOT_TOKEN",
  "TELEGRAM_CHAT_ID",
  "GMAIL_USER",
  "GMAIL_APP_PASS",
  "SIGNFLOW_API_KEY",
  "LEGAL_TECH_API_TOKEN",
]);

function listTenants() {
  if (!fs.existsSync(tenantsDir)) return [];
  return fs
    .readdirSync(tenantsDir)
    .filter((f) => f.endsWith(".env") && !f.startsWith("_"))
    .map((f) => f.replace(/\.env$/, ""));
}

const arg = process.argv[2];
if (!arg || arg === "list") {
  console.log("Available tenants:\n");
  for (const name of listTenants()) {
    console.log(`  ${name}`);
  }
  console.log("\nUsage: npm run tenant -- <name>");
  console.log("Example: npm run tenant -- trustnest");
  process.exit(arg === "list" ? 0 : 1);
}

const tenantFile = path.join(tenantsDir, `${arg}.env`);
if (!fs.existsSync(tenantFile)) {
  console.error(`Unknown tenant "${arg}". Available: ${listTenants().join(", ")}`);
  process.exit(1);
}

const basePaths = [".env", ".env.local"].map((f) => path.join(root, f));
let merged = {};
for (const p of basePaths) {
  if (fs.existsSync(p)) {
    merged = { ...merged, ...parseEnv(fs.readFileSync(p, "utf8")) };
  }
}

const tenant = parseEnv(fs.readFileSync(tenantFile, "utf8"));
for (const [k, v] of Object.entries(tenant)) {
  if (SECRET_KEYS.has(k)) continue;
  merged[k] = v;
}

const outPath = path.join(root, ".env.local");
const header = `# Generated by switch-tenant (${arg}) — ${new Date().toISOString()}\n# Secrets from .env are preserved. Restart: npm run dev:fresh`;
fs.writeFileSync(outPath, stringifyEnv(merged, header), "utf8");

const callback = `${merged.NEXTAUTH_URL || merged.NEXT_PUBLIC_APP_URL || "http://localhost:3000"}`.replace(
  /\/+$/,
  ""
);
console.log(`\nSwitched to tenant: ${arg}`);
console.log(`Wrote ${outPath}`);
console.log(`Brand: ${merged.NEXT_PUBLIC_BRAND_NAME || "(default)"}`);
console.log(`\nGoogle Console — add redirect URI if needed:\n  ${callback}/api/auth/callback/google\n`);
console.log("Restart dev server: npm run dev:fresh\n");
