export type ElementCategory =
  | "nonmetal" | "noble-gas" | "alkali-metal" | "alkaline-earth"
  | "transition-metal" | "post-transition" | "metalloid" | "halogen"
  | "lanthanide" | "actinide" | "unknown";

export interface ChemElement {
  atomicNumber: number;
  symbol: string;
  name: string;
  atomicMass: number;
  category: ElementCategory;
  group: number | null;
  period: number;
  electronegativity: number | null;
  electronConfiguration: string;
  oxidationStates: number[];
  meltingPoint: number | null;
  boilingPoint: number | null;
  discoveryYear: number | null;
  discoveredBy: string | null;
  phase: "solid" | "liquid" | "gas" | "unknown";
  radioactive: boolean;
  shells: number[];
  summary: string;
}

export const ELEMENTS: ChemElement[] = [
  { atomicNumber:1,  symbol:"H",  name:"Hydrogen",     atomicMass:1.008,   category:"nonmetal",        group:1,  period:1, electronegativity:2.20, electronConfiguration:"1s¹",              oxidationStates:[-1,1],    meltingPoint:13.99,  boilingPoint:20.27,  discoveryYear:1766, discoveredBy:"Henry Cavendish", phase:"gas",  radioactive:false, shells:[1],          summary:"The lightest and most abundant element in the universe. Forms water (H₂O) with oxygen and is essential to life. Used in fuel cells, petroleum refining, and as a rocket propellant." },
  { atomicNumber:2,  symbol:"He", name:"Helium",        atomicMass:4.003,   category:"noble-gas",       group:18, period:1, electronegativity:null, electronConfiguration:"1s²",              oxidationStates:[0],       meltingPoint:0.95,   boilingPoint:4.22,   discoveryYear:1868, discoveredBy:"Pierre Janssen",  phase:"gas",  radioactive:false, shells:[2],          summary:"A colorless, odorless noble gas with the lowest boiling point of any element. Used in balloons, as a cryogenic coolant for MRI machines, and in pressurizing rocket fuel." },
  { atomicNumber:3,  symbol:"Li", name:"Lithium",       atomicMass:6.941,   category:"alkali-metal",    group:1,  period:2, electronegativity:0.98, electronConfiguration:"[He] 2s¹",         oxidationStates:[1],       meltingPoint:453.69, boilingPoint:1615,   discoveryYear:1817, discoveredBy:"Johan August Arfwedson", phase:"solid", radioactive:false, shells:[2,1],        summary:"Lightest metal and solid element. Critical component of rechargeable batteries. Used in mood-stabilizing medications, alloys, and nuclear reactors." },
  { atomicNumber:4,  symbol:"Be", name:"Beryllium",     atomicMass:9.012,   category:"alkaline-earth",  group:2,  period:2, electronegativity:1.57, electronConfiguration:"[He] 2s²",         oxidationStates:[2],       meltingPoint:1560,   boilingPoint:2742,   discoveryYear:1798, discoveredBy:"Louis-Nicolas Vauquelin", phase:"solid", radioactive:false, shells:[2,2],        summary:"A hard, lightweight steel-grey metal used in aerospace components, X-ray windows, and nuclear reactors. Highly toxic if inhaled as dust." },
  { atomicNumber:5,  symbol:"B",  name:"Boron",         atomicMass:10.811,  category:"metalloid",       group:13, period:2, electronegativity:2.04, electronConfiguration:"[He] 2s² 2p¹",     oxidationStates:[3],       meltingPoint:2349,   boilingPoint:4200,   discoveryYear:1808, discoveredBy:"Humphry Davy",    phase:"solid", radioactive:false, shells:[2,3],        summary:"A metalloid essential for plant growth. Used in borosilicate glass (Pyrex), insulation fiberglass, neodymium magnets, and as a neutron absorber in nuclear reactors." },
  { atomicNumber:6,  symbol:"C",  name:"Carbon",        atomicMass:12.011,  category:"nonmetal",        group:14, period:2, electronegativity:2.55, electronConfiguration:"[He] 2s² 2p²",     oxidationStates:[-4,2,4],  meltingPoint:3800,   boilingPoint:4300,   discoveryYear:null, discoveredBy:null,              phase:"solid", radioactive:false, shells:[2,4],        summary:"The basis of all organic chemistry and life on Earth. Exists as graphite, diamond, graphene, and fullerenes. Carbon dating is used to determine the age of organic materials." },
  { atomicNumber:7,  symbol:"N",  name:"Nitrogen",      atomicMass:14.007,  category:"nonmetal",        group:15, period:2, electronegativity:3.04, electronConfiguration:"[He] 2s² 2p³",     oxidationStates:[-3,3,5],  meltingPoint:63.15,  boilingPoint:77.36,  discoveryYear:1772, discoveredBy:"Daniel Rutherford", phase:"gas", radioactive:false, shells:[2,5],        summary:"Makes up 78% of Earth's atmosphere. Essential component of amino acids, DNA, and proteins. Used in fertilizers, explosives, and as an inert atmosphere in industrial processes." },
  { atomicNumber:8,  symbol:"O",  name:"Oxygen",        atomicMass:15.999,  category:"nonmetal",        group:16, period:2, electronegativity:3.44, electronConfiguration:"[He] 2s² 2p⁴",     oxidationStates:[-2,-1],   meltingPoint:54.36,  boilingPoint:90.20,  discoveryYear:1774, discoveredBy:"Carl Wilhelm Scheele", phase:"gas", radioactive:false, shells:[2,6],        summary:"Second most abundant element in Earth's crust and the most abundant in the human body. Essential for respiration and combustion. Liquid oxygen is used as a rocket oxidizer." },
  { atomicNumber:9,  symbol:"F",  name:"Fluorine",      atomicMass:18.998,  category:"halogen",         group:17, period:2, electronegativity:3.98, electronConfiguration:"[He] 2s² 2p⁵",     oxidationStates:[-1],      meltingPoint:53.48,  boilingPoint:85.03,  discoveryYear:1886, discoveredBy:"Henri Moissan",   phase:"gas",  radioactive:false, shells:[2,7],        summary:"The most electronegative and reactive nonmetal. Used in fluoride toothpaste, Teflon, and refrigerants. Its compounds are used to enrich uranium for nuclear fuel." },
  { atomicNumber:10, symbol:"Ne", name:"Neon",          atomicMass:20.180,  category:"noble-gas",       group:18, period:2, electronegativity:null, electronConfiguration:"[He] 2s² 2p⁶",     oxidationStates:[0],       meltingPoint:24.56,  boilingPoint:27.10,  discoveryYear:1898, discoveredBy:"William Ramsay",  phase:"gas",  radioactive:false, shells:[2,8],        summary:"Famous for its bright red-orange glow in discharge tubes used for 'neon signs.' The fifth most abundant element in the universe, but rare on Earth." },
  { atomicNumber:11, symbol:"Na", name:"Sodium",        atomicMass:22.990,  category:"alkali-metal",    group:1,  period:3, electronegativity:0.93, electronConfiguration:"[Ne] 3s¹",         oxidationStates:[1],       meltingPoint:370.87, boilingPoint:1156,   discoveryYear:1807, discoveredBy:"Humphry Davy",    phase:"solid", radioactive:false, shells:[2,8,1],      summary:"A soft, silvery-white alkali metal. Essential for nerve function and osmotic balance in living organisms. Sodium chloride (table salt) is one of the most important chemicals." },
  { atomicNumber:12, symbol:"Mg", name:"Magnesium",     atomicMass:24.305,  category:"alkaline-earth",  group:2,  period:3, electronegativity:1.31, electronConfiguration:"[Ne] 3s²",         oxidationStates:[2],       meltingPoint:923,    boilingPoint:1363,   discoveryYear:1755, discoveredBy:"Joseph Black",    phase:"solid", radioactive:false, shells:[2,8,2],      summary:"A shiny gray metal that burns with a brilliant white flame. Essential for chlorophyll in plants. Used in lightweight alloys for aerospace, automotive, and sports equipment." },
  { atomicNumber:13, symbol:"Al", name:"Aluminium",     atomicMass:26.982,  category:"post-transition", group:13, period:3, electronegativity:1.61, electronConfiguration:"[Ne] 3s² 3p¹",     oxidationStates:[3],       meltingPoint:933.47, boilingPoint:2792,   discoveryYear:1825, discoveredBy:"Hans Christian Ørsted", phase:"solid", radioactive:false, shells:[2,8,3],      summary:"The most abundant metal in Earth's crust. Lightweight, corrosion-resistant, and highly recyclable. Used in packaging, transportation, construction, and electrical wiring." },
  { atomicNumber:14, symbol:"Si", name:"Silicon",       atomicMass:28.086,  category:"metalloid",       group:14, period:3, electronegativity:1.90, electronConfiguration:"[Ne] 3s² 3p²",     oxidationStates:[-4,4],    meltingPoint:1687,   boilingPoint:3538,   discoveryYear:1824, discoveredBy:"Jöns Jacob Berzelius", phase:"solid", radioactive:false, shells:[2,8,4],      summary:"The second most abundant element in Earth's crust and the backbone of the semiconductor industry. Silicon chips power all modern computers and electronics." },
  { atomicNumber:15, symbol:"P",  name:"Phosphorus",    atomicMass:30.974,  category:"nonmetal",        group:15, period:3, electronegativity:2.19, electronConfiguration:"[Ne] 3s² 3p³",     oxidationStates:[-3,3,5],  meltingPoint:317.30, boilingPoint:550,    discoveryYear:1669, discoveredBy:"Hennig Brand",    phase:"solid", radioactive:false, shells:[2,8,5],      summary:"Essential element for life, found in DNA, RNA, ATP, and bones. White phosphorus is highly toxic and flammable; red phosphorus is used in safety matches." },
  { atomicNumber:16, symbol:"S",  name:"Sulfur",        atomicMass:32.065,  category:"nonmetal",        group:16, period:3, electronegativity:2.58, electronConfiguration:"[Ne] 3s² 3p⁴",     oxidationStates:[-2,2,4,6],meltingPoint:388.36, boilingPoint:717.87, discoveryYear:null, discoveredBy:null,              phase:"solid", radioactive:false, shells:[2,8,6],      summary:"A bright yellow solid known since ancient times as 'brimstone.' Essential for amino acids and proteins. Used in gunpowder, matches, insecticides, and sulfuric acid production." },
  { atomicNumber:17, symbol:"Cl", name:"Chlorine",      atomicMass:35.453,  category:"halogen",         group:17, period:3, electronegativity:3.16, electronConfiguration:"[Ne] 3s² 3p⁵",     oxidationStates:[-1,1,3,5,7], meltingPoint:171.60, boilingPoint:239.11, discoveryYear:1774, discoveredBy:"Carl Wilhelm Scheele", phase:"gas", radioactive:false, shells:[2,8,7],      summary:"A toxic yellow-green gas used as a disinfectant in water treatment and swimming pools. Combined with sodium to form table salt. Used in the production of PVC plastic." },
  { atomicNumber:18, symbol:"Ar", name:"Argon",         atomicMass:39.948,  category:"noble-gas",       group:18, period:3, electronegativity:null, electronConfiguration:"[Ne] 3s² 3p⁶",     oxidationStates:[0],       meltingPoint:83.80,  boilingPoint:87.30,  discoveryYear:1894, discoveredBy:"Lord Rayleigh",   phase:"gas",  radioactive:false, shells:[2,8,8],      summary:"The third most abundant gas in Earth's atmosphere. Used as an inert shielding gas in welding, as a fill gas in incandescent light bulbs, and in semiconductor manufacturing." },
  { atomicNumber:19, symbol:"K",  name:"Potassium",     atomicMass:39.098,  category:"alkali-metal",    group:1,  period:4, electronegativity:0.82, electronConfiguration:"[Ar] 4s¹",         oxidationStates:[1],       meltingPoint:336.53, boilingPoint:1032,   discoveryYear:1807, discoveredBy:"Humphry Davy",    phase:"solid", radioactive:false, shells:[2,8,8,1],    summary:"An essential mineral for human health, critical for heart function and nerve signals. The third most abundant mineral in the body. Used in fertilizers and food preservation." },
  { atomicNumber:20, symbol:"Ca", name:"Calcium",       atomicMass:40.078,  category:"alkaline-earth",  group:2,  period:4, electronegativity:1.00, electronConfiguration:"[Ar] 4s²",         oxidationStates:[2],       meltingPoint:1115,   boilingPoint:1757,   discoveryYear:1808, discoveredBy:"Humphry Davy",    phase:"solid", radioactive:false, shells:[2,8,8,2],    summary:"The fifth most abundant element in Earth's crust. Essential for building bones and teeth. Used in cement, steel production, and as a reducing agent in metallurgy." },
  { atomicNumber:21, symbol:"Sc", name:"Scandium",      atomicMass:44.956,  category:"transition-metal",group:3,  period:4, electronegativity:1.36, electronConfiguration:"[Ar] 3d¹ 4s²",     oxidationStates:[3],       meltingPoint:1814,   boilingPoint:3109,   discoveryYear:1879, discoveredBy:"Lars Fredrik Nilson", phase:"solid", radioactive:false, shells:[2,8,9,2],    summary:"A silvery-white transition metal used in high-intensity discharge lamps and as a lightweight alloying agent in aerospace components. Scandium-aluminum alloys are used in aircraft and sporting equipment." },
  { atomicNumber:22, symbol:"Ti", name:"Titanium",      atomicMass:47.867,  category:"transition-metal",group:4,  period:4, electronegativity:1.54, electronConfiguration:"[Ar] 3d² 4s²",     oxidationStates:[2,3,4],   meltingPoint:1941,   boilingPoint:3560,   discoveryYear:1791, discoveredBy:"William Gregor",  phase:"solid", radioactive:false, shells:[2,8,10,2],   summary:"Strong, lightweight, and corrosion-resistant metal used in aerospace, medical implants, and jewelry. Titanium dioxide is used as a white pigment in paints and sunscreens." },
  { atomicNumber:23, symbol:"V",  name:"Vanadium",      atomicMass:50.942,  category:"transition-metal",group:5,  period:4, electronegativity:1.63, electronConfiguration:"[Ar] 3d³ 4s²",     oxidationStates:[2,3,4,5], meltingPoint:2183,   boilingPoint:3680,   discoveryYear:1801, discoveredBy:"Andrés Manuel del Río", phase:"solid", radioactive:false, shells:[2,8,11,2],   summary:"A hard, silvery-grey metal used to make steel alloys that are stronger and more corrosion-resistant. Vanadium redox batteries are used in large-scale energy storage." },
  { atomicNumber:24, symbol:"Cr", name:"Chromium",      atomicMass:51.996,  category:"transition-metal",group:6,  period:4, electronegativity:1.66, electronConfiguration:"[Ar] 3d⁵ 4s¹",     oxidationStates:[2,3,6],   meltingPoint:2180,   boilingPoint:2944,   discoveryYear:1798, discoveredBy:"Louis Nicolas Vauquelin", phase:"solid", radioactive:false, shells:[2,8,13,1],   summary:"A hard, lustrous metal known for its high shine. Chromium plating protects metals from rust. Combined with iron and nickel to make stainless steel. Chromium(III) is an essential trace nutrient." },
  { atomicNumber:25, symbol:"Mn", name:"Manganese",     atomicMass:54.938,  category:"transition-metal",group:7,  period:4, electronegativity:1.55, electronConfiguration:"[Ar] 3d⁵ 4s²",     oxidationStates:[2,3,4,7], meltingPoint:1519,   boilingPoint:2334,   discoveryYear:1774, discoveredBy:"Johan Gottlieb Gahn", phase:"solid", radioactive:false, shells:[2,8,13,2],   summary:"A brittle, silvery metal essential for steel production. Used in alkaline batteries, as a pigment (manganese violet), and as a micronutrient for plant growth and human health." },
  { atomicNumber:26, symbol:"Fe", name:"Iron",          atomicMass:55.845,  category:"transition-metal",group:8,  period:4, electronegativity:1.83, electronConfiguration:"[Ar] 3d⁶ 4s²",     oxidationStates:[2,3],     meltingPoint:1811,   boilingPoint:3134,   discoveryYear:null, discoveredBy:null,              phase:"solid", radioactive:false, shells:[2,8,14,2],   summary:"The most used metal in the world, forming the basis of steel. Earth's core is primarily iron. Essential for hemoglobin which transports oxygen in blood. Has been used by humans for over 3000 years." },
  { atomicNumber:27, symbol:"Co", name:"Cobalt",        atomicMass:58.933,  category:"transition-metal",group:9,  period:4, electronegativity:1.88, electronConfiguration:"[Ar] 3d⁷ 4s²",     oxidationStates:[2,3],     meltingPoint:1768,   boilingPoint:3200,   discoveryYear:1735, discoveredBy:"Georg Brandt",    phase:"solid", radioactive:false, shells:[2,8,15,2],   summary:"A hard, lustrous blue-grey metal used in superalloys for jet engines and as a binder in carbide cutting tools. Cobalt blue is a well-known pigment. Essential component of vitamin B12." },
  { atomicNumber:28, symbol:"Ni", name:"Nickel",        atomicMass:58.693,  category:"transition-metal",group:10, period:4, electronegativity:1.91, electronConfiguration:"[Ar] 3d⁸ 4s²",     oxidationStates:[2,3],     meltingPoint:1728,   boilingPoint:3186,   discoveryYear:1751, discoveredBy:"Axel Fredrik Cronstedt", phase:"solid", radioactive:false, shells:[2,8,16,2],   summary:"A silvery-white metal used for corrosion-resistant coatings and in making stainless steel. Nickel-cadmium and nickel-metal hydride batteries are common rechargeable battery types." },
  { atomicNumber:29, symbol:"Cu", name:"Copper",        atomicMass:63.546,  category:"transition-metal",group:11, period:4, electronegativity:1.90, electronConfiguration:"[Ar] 3d¹⁰ 4s¹",    oxidationStates:[1,2],     meltingPoint:1357.77,boilingPoint:2835,   discoveryYear:null, discoveredBy:null,              phase:"solid", radioactive:false, shells:[2,8,18,1],   summary:"One of the oldest metals used by humans, known for its reddish color and high electrical and thermal conductivity. Essential for electrical wiring, plumbing, and as an antimicrobial surface." },
  { atomicNumber:30, symbol:"Zn", name:"Zinc",          atomicMass:65.38,   category:"transition-metal",group:12, period:4, electronegativity:1.65, electronConfiguration:"[Ar] 3d¹⁰ 4s²",    oxidationStates:[2],       meltingPoint:692.68, boilingPoint:1180,   discoveryYear:1746, discoveredBy:"Andreas Sigismund Marggraf", phase:"solid", radioactive:false, shells:[2,8,18,2],   summary:"A bluish-white metal used to galvanize iron and steel to prevent rusting. Essential trace element for immune function and wound healing. Used in dry cell batteries and brass alloys." },
  { atomicNumber:31, symbol:"Ga", name:"Gallium",       atomicMass:69.723,  category:"post-transition", group:13, period:4, electronegativity:1.81, electronConfiguration:"[Ar] 3d¹⁰ 4s² 4p¹",oxidationStates:[3],       meltingPoint:302.91, boilingPoint:2673,   discoveryYear:1875, discoveredBy:"Paul Emile Lecoq de Boisbaudran", phase:"solid", radioactive:false, shells:[2,8,18,3],   summary:"A soft metal that melts just above room temperature (29.8°C). Gallium arsenide is used in LEDs, solar cells, and high-speed semiconductors. Can melt in the palm of your hand." },
  { atomicNumber:32, symbol:"Ge", name:"Germanium",     atomicMass:72.630,  category:"metalloid",       group:14, period:4, electronegativity:2.01, electronConfiguration:"[Ar] 3d¹⁰ 4s² 4p²",oxidationStates:[2,4],     meltingPoint:1211.4, boilingPoint:3106,   discoveryYear:1886, discoveredBy:"Clemens Winkler",  phase:"solid", radioactive:false, shells:[2,8,18,4],   summary:"A semiconductor metalloid predicted by Mendeleev as 'eka-silicon.' Used in fiber optic cables, infrared optics, solar cells, and was the first material used in transistors." },
  { atomicNumber:33, symbol:"As", name:"Arsenic",       atomicMass:74.922,  category:"metalloid",       group:15, period:4, electronegativity:2.18, electronConfiguration:"[Ar] 3d¹⁰ 4s² 4p³",oxidationStates:[-3,3,5],  meltingPoint:1090,   boilingPoint:887,    discoveryYear:null, discoveredBy:null,              phase:"solid", radioactive:false, shells:[2,8,18,5],   summary:"A highly toxic metalloid infamous as a poison throughout history. Used in wood preservatives, semiconductor dopants, and historically in pigments. Gallium arsenide is used in electronics." },
  { atomicNumber:34, symbol:"Se", name:"Selenium",      atomicMass:78.971,  category:"nonmetal",        group:16, period:4, electronegativity:2.55, electronConfiguration:"[Ar] 3d¹⁰ 4s² 4p⁴",oxidationStates:[-2,2,4,6],meltingPoint:494,    boilingPoint:958,    discoveryYear:1817, discoveredBy:"Jöns Jacob Berzelius", phase:"solid", radioactive:false, shells:[2,8,18,6],   summary:"A nonmetal with photovoltaic and photoconductive properties. Used in photocells, solar cells, and photocopiers. An essential trace element for humans at low doses, but toxic at higher doses." },
  { atomicNumber:35, symbol:"Br", name:"Bromine",       atomicMass:79.904,  category:"halogen",         group:17, period:4, electronegativity:2.96, electronConfiguration:"[Ar] 3d¹⁰ 4s² 4p⁵",oxidationStates:[-1,1,3,5],meltingPoint:265.80, boilingPoint:332,    discoveryYear:1826, discoveredBy:"Antoine Jérôme Balard", phase:"liquid", radioactive:false, shells:[2,8,18,7],   summary:"One of only two elements that is liquid at room temperature. A reddish-brown fuming liquid with an unpleasant smell. Used in flame retardants, pharmaceuticals, and historically in photographic film." },
  { atomicNumber:36, symbol:"Kr", name:"Krypton",       atomicMass:83.798,  category:"noble-gas",       group:18, period:4, electronegativity:null, electronConfiguration:"[Ar] 3d¹⁰ 4s² 4p⁶",oxidationStates:[0,2],     meltingPoint:115.79, boilingPoint:119.93, discoveryYear:1898, discoveredBy:"William Ramsay",  phase:"gas",  radioactive:false, shells:[2,8,18,8],   summary:"A noble gas used in high-performance flash photography, some fluorescent lights, and as an insulating gas in energy-efficient windows. Has been used to define the meter standard." },
  { atomicNumber:37, symbol:"Rb", name:"Rubidium",      atomicMass:85.468,  category:"alkali-metal",    group:1,  period:5, electronegativity:0.82, electronConfiguration:"[Kr] 5s¹",         oxidationStates:[1],       meltingPoint:312.46, boilingPoint:961,    discoveryYear:1861, discoveredBy:"Robert Bunsen",   phase:"solid", radioactive:false, shells:[2,8,18,8,1], summary:"A soft, silvery alkali metal that ignites spontaneously in air. Used in atomic clocks (highly accurate timekeeping), ion propulsion systems, and medical imaging." },
  { atomicNumber:38, symbol:"Sr", name:"Strontium",     atomicMass:87.62,   category:"alkaline-earth",  group:2,  period:5, electronegativity:0.95, electronConfiguration:"[Kr] 5s²",         oxidationStates:[2],       meltingPoint:1050,   boilingPoint:1655,   discoveryYear:1790, discoveredBy:"William Cruickshank", phase:"solid", radioactive:false, shells:[2,8,18,8,2], summary:"A silvery-white alkaline earth metal that burns with a bright red flame. Used in fireworks and signal flares. Strontium-90 is a radioactive fission product from nuclear reactors." },
  { atomicNumber:39, symbol:"Y",  name:"Yttrium",       atomicMass:88.906,  category:"transition-metal",group:3,  period:5, electronegativity:1.22, electronConfiguration:"[Kr] 4d¹ 5s²",     oxidationStates:[3],       meltingPoint:1799,   boilingPoint:3609,   discoveryYear:1794, discoveredBy:"Johan Gadolin",   phase:"solid", radioactive:false, shells:[2,8,18,9,2], summary:"A silvery-metallic transition metal used in LED phosphors (giving the white light in white LEDs), superalloys, and as the red phosphor in cathode ray tube TVs." },
  { atomicNumber:40, symbol:"Zr", name:"Zirconium",     atomicMass:91.224,  category:"transition-metal",group:4,  period:5, electronegativity:1.33, electronConfiguration:"[Kr] 4d² 5s²",     oxidationStates:[2,3,4],   meltingPoint:2128,   boilingPoint:4682,   discoveryYear:1789, discoveredBy:"Martin Heinrich Klaproth", phase:"solid", radioactive:false, shells:[2,8,18,10,2],summary:"A lustrous, greyish-white metal known for exceptional corrosion resistance and low neutron-capture cross-section. Used as cladding for nuclear reactor fuel rods and in cubic zirconia gemstones." },
  { atomicNumber:41, symbol:"Nb", name:"Niobium",       atomicMass:92.906,  category:"transition-metal",group:5,  period:5, electronegativity:1.60, electronConfiguration:"[Kr] 4d⁴ 5s¹",     oxidationStates:[3,5],     meltingPoint:2750,   boilingPoint:5017,   discoveryYear:1801, discoveredBy:"Charles Hatchett", phase:"solid", radioactive:false, shells:[2,8,18,12,1],summary:"A soft, grey, ductile metal used in superalloys for jet engines and rocket components. Also used to make superconducting magnets for MRI machines when alloyed with tin." },
  { atomicNumber:42, symbol:"Mo", name:"Molybdenum",    atomicMass:95.96,   category:"transition-metal",group:6,  period:5, electronegativity:2.16, electronConfiguration:"[Kr] 4d⁵ 5s¹",     oxidationStates:[2,3,4,6], meltingPoint:2896,   boilingPoint:4912,   discoveryYear:1781, discoveredBy:"Carl Wilhelm Scheele", phase:"solid", radioactive:false, shells:[2,8,18,13,1],summary:"A hard, silvery metal with one of the highest melting points of all elements. Used in high-strength steel alloys, lubricants (MoS₂), and as a catalyst in the petroleum industry." },
  { atomicNumber:43, symbol:"Tc", name:"Technetium",    atomicMass:98,      category:"transition-metal",group:7,  period:5, electronegativity:1.90, electronConfiguration:"[Kr] 4d⁵ 5s²",     oxidationStates:[2,4,6,7], meltingPoint:2430,   boilingPoint:4538,   discoveryYear:1937, discoveredBy:"Carlo Perrier",   phase:"solid", radioactive:true,  shells:[2,8,18,13,2],summary:"The first artificially produced element and the lightest element with no stable isotopes. Technetium-99m is widely used as a radioactive tracer in nuclear medicine diagnostics." },
  { atomicNumber:44, symbol:"Ru", name:"Ruthenium",     atomicMass:101.07,  category:"transition-metal",group:8,  period:5, electronegativity:2.20, electronConfiguration:"[Kr] 4d⁷ 5s¹",     oxidationStates:[2,3,4,6,8],meltingPoint:2607,  boilingPoint:4423,   discoveryYear:1844, discoveredBy:"Karl Ernst Claus", phase:"solid", radioactive:false, shells:[2,8,18,15,1],summary:"A rare platinum-group metal used as a hardener for platinum and palladium in electrical contacts. Ruthenium complexes are used in solar energy conversion and cancer treatment research." },
  { atomicNumber:45, symbol:"Rh", name:"Rhodium",       atomicMass:102.906, category:"transition-metal",group:9,  period:5, electronegativity:2.28, electronConfiguration:"[Kr] 4d⁸ 5s¹",     oxidationStates:[1,3],     meltingPoint:2237,   boilingPoint:3968,   discoveryYear:1803, discoveredBy:"William Hyde Wollaston", phase:"solid", radioactive:false, shells:[2,8,18,16,1],summary:"One of the rarest and most valuable precious metals. Used as a catalyst in three-way catalytic converters for reducing vehicle emissions. Also used in jewelry as a bright, reflective coating." },
  { atomicNumber:46, symbol:"Pd", name:"Palladium",     atomicMass:106.42,  category:"transition-metal",group:10, period:5, electronegativity:2.20, electronConfiguration:"[Kr] 4d¹⁰",        oxidationStates:[2,4],     meltingPoint:1828.05,boilingPoint:3236,   discoveryYear:1803, discoveredBy:"William Hyde Wollaston", phase:"solid", radioactive:false, shells:[2,8,18,18],  summary:"A silvery-white noble metal used as a catalyst in catalytic converters, hydrogen purification, and in jewelry. Has the remarkable ability to absorb up to 900 times its own volume of hydrogen." },
  { atomicNumber:47, symbol:"Ag", name:"Silver",        atomicMass:107.868, category:"transition-metal",group:11, period:5, electronegativity:1.93, electronConfiguration:"[Kr] 4d¹⁰ 5s¹",    oxidationStates:[1],       meltingPoint:1234.93,boilingPoint:2435,   discoveryYear:null, discoveredBy:null,              phase:"solid", radioactive:false, shells:[2,8,18,18,1],summary:"The metal with the highest electrical and thermal conductivity. Used in jewelry, photography, electronics, and as an antimicrobial agent. Has been used as currency for thousands of years." },
  { atomicNumber:48, symbol:"Cd", name:"Cadmium",       atomicMass:112.411, category:"transition-metal",group:12, period:5, electronegativity:1.69, electronConfiguration:"[Kr] 4d¹⁰ 5s²",    oxidationStates:[2],       meltingPoint:594.22, boilingPoint:1040,   discoveryYear:1817, discoveredBy:"Friedrich Stromeyer", phase:"solid", radioactive:false, shells:[2,8,18,18,2],summary:"A toxic soft bluish-white metal used in nickel-cadmium rechargeable batteries and as a yellow/orange pigment in paints. Also used in control rods for nuclear reactors. Highly toxic to ecosystems." },
  { atomicNumber:49, symbol:"In", name:"Indium",        atomicMass:114.818, category:"post-transition", group:13, period:5, electronegativity:1.78, electronConfiguration:"[Kr] 4d¹⁰ 5s² 5p¹",oxidationStates:[3],       meltingPoint:429.75, boilingPoint:2345,   discoveryYear:1863, discoveredBy:"Ferdinand Reich",  phase:"solid", radioactive:false, shells:[2,8,18,18,3],summary:"A soft, silvery-white post-transition metal. Indium tin oxide (ITO) is used as a transparent conductor in touchscreens and flat-panel displays. Emits a high-pitched scream when bent." },
  { atomicNumber:50, symbol:"Sn", name:"Tin",           atomicMass:118.710, category:"post-transition", group:14, period:5, electronegativity:1.96, electronConfiguration:"[Kr] 4d¹⁰ 5s² 5p²",oxidationStates:[2,4],     meltingPoint:505.08, boilingPoint:2875,   discoveryYear:null, discoveredBy:null,              phase:"solid", radioactive:false, shells:[2,8,18,18,4],summary:"A soft, silvery metal known since ancient times. Tin-bronze alloy enabled the Bronze Age. Used in food can coatings, solder, and pewter. 'Tin cry' is the crackling sound it makes when bent." },
  { atomicNumber:51, symbol:"Sb", name:"Antimony",      atomicMass:121.760, category:"metalloid",       group:15, period:5, electronegativity:2.05, electronConfiguration:"[Kr] 4d¹⁰ 5s² 5p³",oxidationStates:[-3,3,5],  meltingPoint:903.78, boilingPoint:1860,   discoveryYear:null, discoveredBy:null,              phase:"solid", radioactive:false, shells:[2,8,18,18,5],summary:"A lustrous grey metalloid known since ancient Egypt as the eye cosmetic kohl. Used in lead-acid batteries, flame retardants, and semiconductor devices. One of the few elements that expands on solidifying." },
  { atomicNumber:52, symbol:"Te", name:"Tellurium",     atomicMass:127.60,  category:"metalloid",       group:16, period:5, electronegativity:2.10, electronConfiguration:"[Kr] 4d¹⁰ 5s² 5p⁴",oxidationStates:[-2,2,4,6],meltingPoint:722.66, boilingPoint:1261,   discoveryYear:1782, discoveredBy:"Franz-Joseph Müller von Reichenstein", phase:"solid", radioactive:false, shells:[2,8,18,18,6],summary:"A rare silvery metalloid used in cadmium telluride solar cells, as an alloying agent in steel and copper, and in thermoelectric devices. Exposure causes a persistent garlic-like body odor." },
  { atomicNumber:53, symbol:"I",  name:"Iodine",        atomicMass:126.904, category:"halogen",         group:17, period:5, electronegativity:2.66, electronConfiguration:"[Kr] 4d¹⁰ 5s² 5p⁵",oxidationStates:[-1,1,3,5,7],meltingPoint:386.85,boilingPoint:457.40, discoveryYear:1811, discoveredBy:"Bernard Courtois",phase:"solid", radioactive:false, shells:[2,8,18,18,7],summary:"A dark violet solid that sublimes to a violet vapor at room temperature. Essential for thyroid hormone production. Used as a disinfectant, in photography, and in iodized salt to prevent goiter." },
  { atomicNumber:54, symbol:"Xe", name:"Xenon",         atomicMass:131.293, category:"noble-gas",       group:18, period:5, electronegativity:2.60, electronConfiguration:"[Kr] 4d¹⁰ 5s² 5p⁶",oxidationStates:[0,2,4,6,8],meltingPoint:161.40,boilingPoint:165.05, discoveryYear:1898, discoveredBy:"William Ramsay",  phase:"gas",  radioactive:false, shells:[2,8,18,18,8],summary:"A noble gas used in flash photography, high-intensity arc lamps for cinema projection, and ion propulsion systems for spacecraft. The first noble gas to form chemical compounds." },
  { atomicNumber:55, symbol:"Cs", name:"Caesium",       atomicMass:132.905, category:"alkali-metal",    group:1,  period:6, electronegativity:0.79, electronConfiguration:"[Xe] 6s¹",         oxidationStates:[1],       meltingPoint:301.59, boilingPoint:944,    discoveryYear:1860, discoveredBy:"Robert Bunsen",   phase:"solid", radioactive:false, shells:[2,8,18,18,8,1],summary:"The softest metal and has the lowest electronegativity. Cesium-133 atomic clocks define the SI second with extreme precision. Used in photoelectric cells and oil drilling." },
  { atomicNumber:56, symbol:"Ba", name:"Barium",        atomicMass:137.327, category:"alkaline-earth",  group:2,  period:6, electronegativity:0.89, electronConfiguration:"[Xe] 6s²",         oxidationStates:[2],       meltingPoint:1000,   boilingPoint:2118,   discoveryYear:1808, discoveredBy:"Humphry Davy",    phase:"solid", radioactive:false, shells:[2,8,18,18,8,2],summary:"A soft silvery alkaline earth metal. Barium sulfate is used as a radiocontrast agent for X-ray imaging of the digestive system. Barium compounds give fireworks a green color." },
  { atomicNumber:57, symbol:"La", name:"Lanthanum",     atomicMass:138.905, category:"lanthanide",      group:null,period:6, electronegativity:1.10, electronConfiguration:"[Xe] 5d¹ 6s²",     oxidationStates:[3],       meltingPoint:1193,   boilingPoint:3737,   discoveryYear:1839, discoveredBy:"Carl Gustaf Mosander", phase:"solid", radioactive:false, shells:[2,8,18,18,9,2],summary:"The first of the lanthanide series. Used in camera and telescope lenses, hydrogen sponge alloys, and as a catalyst in oil refining. La₂O₃ is used to make optical glass with high refractive index." },
  { atomicNumber:58, symbol:"Ce", name:"Cerium",        atomicMass:140.116, category:"lanthanide",      group:null,period:6, electronegativity:1.12, electronConfiguration:"[Xe] 4f¹ 5d¹ 6s²", oxidationStates:[3,4],     meltingPoint:1068,   boilingPoint:3716,   discoveryYear:1803, discoveredBy:"Wilhelm Hisinger", phase:"solid", radioactive:false, shells:[2,8,18,19,9,2],summary:"The most abundant rare earth element. Cerium oxide is used to polish glass lenses and as a catalyst in catalytic converters. Cerium-based compounds are used in self-cleaning ovens." },
  { atomicNumber:59, symbol:"Pr", name:"Praseodymium",  atomicMass:140.908, category:"lanthanide",      group:null,period:6, electronegativity:1.13, electronConfiguration:"[Xe] 4f³ 6s²",     oxidationStates:[3,4],     meltingPoint:1208,   boilingPoint:3793,   discoveryYear:1885, discoveredBy:"Carl Auer von Welsbach", phase:"solid", radioactive:false, shells:[2,8,18,21,8,2],summary:"A soft, silvery, malleable lanthanide used to create strong permanent magnets (praseodymium-iron-boron) and high-power lasers. The name means 'green twin' due to its green salts." },
  { atomicNumber:60, symbol:"Nd", name:"Neodymium",     atomicMass:144.242, category:"lanthanide",      group:null,period:6, electronegativity:1.14, electronConfiguration:"[Xe] 4f⁴ 6s²",     oxidationStates:[3],       meltingPoint:1297,   boilingPoint:3347,   discoveryYear:1885, discoveredBy:"Carl Auer von Welsbach", phase:"solid", radioactive:false, shells:[2,8,18,22,8,2],summary:"Used in the strongest permanent magnets (neodymium-iron-boron), which are in hard drives, earphones, and electric motors. The name means 'new twin' as it was separated from praseodymium." },
  { atomicNumber:61, symbol:"Pm", name:"Promethium",    atomicMass:145,     category:"lanthanide",      group:null,period:6, electronegativity:1.13, electronConfiguration:"[Xe] 4f⁵ 6s²",     oxidationStates:[3],       meltingPoint:1315,   boilingPoint:3273,   discoveryYear:1945, discoveredBy:"Jacob A. Marinsky", phase:"solid", radioactive:true,  shells:[2,8,18,23,8,2],summary:"The only naturally radioactive lanthanide with no stable isotopes. Named after Prometheus. Used as a beta radiation source in luminous paints and atomic batteries for spacecraft." },
  { atomicNumber:62, symbol:"Sm", name:"Samarium",      atomicMass:150.36,  category:"lanthanide",      group:null,period:6, electronegativity:1.17, electronConfiguration:"[Xe] 4f⁶ 6s²",     oxidationStates:[2,3],     meltingPoint:1345,   boilingPoint:2067,   discoveryYear:1879, discoveredBy:"Paul Emile Lecoq de Boisbaudran", phase:"solid", radioactive:false, shells:[2,8,18,24,8,2],summary:"Named after the mineral samarskite. Samarium-cobalt magnets were the first rare earth magnets discovered, used in high-performance motors and headphones. Sm-153 is used in cancer pain treatment." },
  { atomicNumber:63, symbol:"Eu", name:"Europium",      atomicMass:151.964, category:"lanthanide",      group:null,period:6, electronegativity:null, electronConfiguration:"[Xe] 4f⁷ 6s²",     oxidationStates:[2,3],     meltingPoint:1099,   boilingPoint:1802,   discoveryYear:1901, discoveredBy:"Eugène-Anatole Demarçay", phase:"solid", radioactive:false, shells:[2,8,18,25,8,2],summary:"A soft, ductile lanthanide used as red and blue phosphors in fluorescent lamps and television screens. Also used in anti-counterfeiting measures in Euro banknotes due to its fluorescent properties." },
  { atomicNumber:64, symbol:"Gd", name:"Gadolinium",    atomicMass:157.25,  category:"lanthanide",      group:null,period:6, electronegativity:1.20, electronConfiguration:"[Xe] 4f⁷ 5d¹ 6s²", oxidationStates:[3],       meltingPoint:1585,   boilingPoint:3546,   discoveryYear:1880, discoveredBy:"Jean Charles Galissard de Marignac", phase:"solid", radioactive:false, shells:[2,8,18,25,9,2],summary:"Has the highest magnetic moment of any naturally occurring element. Gadolinium contrast agents are widely used in MRI scans. Named after the Finnish chemist Johan Gadolin." },
  { atomicNumber:65, symbol:"Tb", name:"Terbium",       atomicMass:158.925, category:"lanthanide",      group:null,period:6, electronegativity:null, electronConfiguration:"[Xe] 4f⁹ 6s²",     oxidationStates:[3,4],     meltingPoint:1629,   boilingPoint:3503,   discoveryYear:1843, discoveredBy:"Carl Gustaf Mosander", phase:"solid", radioactive:false, shells:[2,8,18,27,8,2],summary:"A silvery-white rare earth metal used in green phosphors for television screens and fluorescent lamps. Terbium-doped materials are used in magnetostrictive alloys (Terfenol-D) for sonar transducers." },
  { atomicNumber:66, symbol:"Dy", name:"Dysprosium",    atomicMass:162.500, category:"lanthanide",      group:null,period:6, electronegativity:1.22, electronConfiguration:"[Xe] 4f¹⁰ 6s²",    oxidationStates:[3],       meltingPoint:1680,   boilingPoint:2840,   discoveryYear:1886, discoveredBy:"Paul Emile Lecoq de Boisbaudran", phase:"solid", radioactive:false, shells:[2,8,18,28,8,2],summary:"A rare earth element whose name means 'hard to get.' Added to neodymium magnets to improve high-temperature performance in electric vehicle motors and wind turbines." },
  { atomicNumber:67, symbol:"Ho", name:"Holmium",       atomicMass:164.930, category:"lanthanide",      group:null,period:6, electronegativity:1.23, electronConfiguration:"[Xe] 4f¹¹ 6s²",    oxidationStates:[3],       meltingPoint:1734,   boilingPoint:2993,   discoveryYear:1878, discoveredBy:"Marc Delafontaine", phase:"solid", radioactive:false, shells:[2,8,18,29,8,2],summary:"Has the highest magnetic strength of any element. Used in nuclear reactor control rods, high-strength magnets, and holmium YAG lasers used in certain medical and dental procedures." },
  { atomicNumber:68, symbol:"Er", name:"Erbium",        atomicMass:167.259, category:"lanthanide",      group:null,period:6, electronegativity:1.24, electronConfiguration:"[Xe] 4f¹² 6s²",    oxidationStates:[3],       meltingPoint:1802,   boilingPoint:3141,   discoveryYear:1843, discoveredBy:"Carl Gustaf Mosander", phase:"solid", radioactive:false, shells:[2,8,18,30,8,2],summary:"A silvery-white lanthanide whose ions are used as signal amplifiers in fiber optic cables (erbium-doped fiber amplifiers), enabling long-distance internet communications. Also used in pink glass." },
  { atomicNumber:69, symbol:"Tm", name:"Thulium",       atomicMass:168.934, category:"lanthanide",      group:null,period:6, electronegativity:1.25, electronConfiguration:"[Xe] 4f¹³ 6s²",    oxidationStates:[2,3],     meltingPoint:1818,   boilingPoint:2223,   discoveryYear:1879, discoveredBy:"Per Teodor Cleve", phase:"solid", radioactive:false, shells:[2,8,18,31,8,2],summary:"The least abundant naturally occurring lanthanide. Tm-170 is used as a radiation source in portable X-ray devices. Named after Thule, the mythological northernmost land in the ancient world." },
  { atomicNumber:70, symbol:"Yb", name:"Ytterbium",     atomicMass:173.054, category:"lanthanide",      group:null,period:6, electronegativity:null, electronConfiguration:"[Xe] 4f¹⁴ 6s²",    oxidationStates:[2,3],     meltingPoint:1097,   boilingPoint:1469,   discoveryYear:1878, discoveredBy:"Jean Charles Galissard de Marignac", phase:"solid", radioactive:false, shells:[2,8,18,32,8,2],summary:"A soft, malleable lanthanide used in atomic clocks (ytterbium optical lattice clocks are among the most accurate), as a dopant in fiber optic cables, and in stainless steel alloys." },
  { atomicNumber:71, symbol:"Lu", name:"Lutetium",      atomicMass:174.967, category:"lanthanide",      group:null,period:6, electronegativity:1.27, electronConfiguration:"[Xe] 4f¹⁴ 5d¹ 6s²", oxidationStates:[3],       meltingPoint:1936,   boilingPoint:3675,   discoveryYear:1907, discoveredBy:"Georges Urbain",  phase:"solid", radioactive:false, shells:[2,8,18,32,9,2],summary:"The last and densest stable lanthanide. Used in positron emission tomography (PET) detectors and as a dopant in certain phosphors. Lu-177 is used in targeted radionuclide therapy for cancer." },
  { atomicNumber:72, symbol:"Hf", name:"Hafnium",       atomicMass:178.49,  category:"transition-metal",group:4,  period:6, electronegativity:1.30, electronConfiguration:"[Xe] 4f¹⁴ 5d² 6s²", oxidationStates:[4],       meltingPoint:2506,   boilingPoint:4876,   discoveryYear:1923, discoveredBy:"Dirk Coster",     phase:"solid", radioactive:false, shells:[2,8,18,32,10,2],summary:"A lustrous silvery metal that is chemically similar to zirconium and is always found with it. Used in nuclear reactor control rods and as a dielectric material in Intel microprocessors." },
  { atomicNumber:73, symbol:"Ta", name:"Tantalum",      atomicMass:180.948, category:"transition-metal",group:5,  period:6, electronegativity:1.50, electronConfiguration:"[Xe] 4f¹⁴ 5d³ 6s²", oxidationStates:[5],       meltingPoint:3290,   boilingPoint:5731,   discoveryYear:1802, discoveredBy:"Anders Gustav Ekeberg", phase:"solid", radioactive:false, shells:[2,8,18,32,11,2],summary:"A rare, hard, blue-grey metal used in tantalum capacitors (essential in mobile phones and computers), surgical instruments, and as a high-temperature alloy component in jet engines." },
  { atomicNumber:74, symbol:"W",  name:"Tungsten",      atomicMass:183.84,  category:"transition-metal",group:6,  period:6, electronegativity:2.36, electronConfiguration:"[Xe] 4f¹⁴ 5d⁴ 6s²", oxidationStates:[2,4,6],   meltingPoint:3695,   boilingPoint:5828,   discoveryYear:1783, discoveredBy:"Juan José Elhuyar", phase:"solid", radioactive:false, shells:[2,8,18,32,12,2],summary:"Has the highest melting point and highest tensile strength of any pure metal. Used in light bulb filaments, X-ray tubes, and as the densest structural metal in armor-piercing ammunition." },
  { atomicNumber:75, symbol:"Re", name:"Rhenium",       atomicMass:186.207, category:"transition-metal",group:7,  period:6, electronegativity:1.90, electronConfiguration:"[Xe] 4f¹⁴ 5d⁵ 6s²", oxidationStates:[4,7],     meltingPoint:3459,   boilingPoint:5869,   discoveryYear:1925, discoveredBy:"Ida Noddack",     phase:"solid", radioactive:false, shells:[2,8,18,32,13,2],summary:"One of the rarest elements in Earth's crust. Used in high-temperature superalloys for jet engine turbine blades and in platinum-rhenium catalysts for the production of unleaded gasoline." },
  { atomicNumber:76, symbol:"Os", name:"Osmium",        atomicMass:190.23,  category:"transition-metal",group:8,  period:6, electronegativity:2.20, electronConfiguration:"[Xe] 4f¹⁴ 5d⁶ 6s²", oxidationStates:[2,4,8],   meltingPoint:3306,   boilingPoint:5285,   discoveryYear:1803, discoveredBy:"Smithson Tennant", phase:"solid", radioactive:false, shells:[2,8,18,32,14,2],summary:"The densest naturally occurring element. Osmium tetroxide has a distinctive smell (its name comes from Greek for 'odor'). Used in fountain pen tips and as a staining agent in electron microscopy." },
  { atomicNumber:77, symbol:"Ir", name:"Iridium",       atomicMass:192.217, category:"transition-metal",group:9,  period:6, electronegativity:2.20, electronConfiguration:"[Xe] 4f¹⁴ 5d⁷ 6s²", oxidationStates:[3,4],     meltingPoint:2719,   boilingPoint:4403,   discoveryYear:1803, discoveredBy:"Smithson Tennant", phase:"solid", radioactive:false, shells:[2,8,18,32,15,2],summary:"The most corrosion-resistant metal. The Cretaceous-Paleogene boundary layer is enriched in iridium, providing evidence for an asteroid impact causing the dinosaur extinction. Used in high-temperature lab equipment." },
  { atomicNumber:78, symbol:"Pt", name:"Platinum",      atomicMass:195.084, category:"transition-metal",group:10, period:6, electronegativity:2.28, electronConfiguration:"[Xe] 4f¹⁴ 5d⁹ 6s¹", oxidationStates:[2,4],     meltingPoint:2041.4, boilingPoint:4098,   discoveryYear:null, discoveredBy:null,              phase:"solid", radioactive:false, shells:[2,8,18,32,17,1],summary:"A precious silver-white metal used in catalytic converters, jewelry, laboratory equipment, and cancer drugs (cisplatin). One of the least reactive metals." },
  { atomicNumber:79, symbol:"Au", name:"Gold",          atomicMass:196.967, category:"transition-metal",group:11, period:6, electronegativity:2.54, electronConfiguration:"[Xe] 4f¹⁴ 5d¹⁰ 6s¹",oxidationStates:[1,3],     meltingPoint:1337.33,boilingPoint:3129,   discoveryYear:null, discoveredBy:null,              phase:"solid", radioactive:false, shells:[2,8,18,32,18,1],summary:"One of the least reactive chemical elements. Used as currency, in jewelry, and in electronics for corrosion-resistant connectors. Gold leaf is used in architecture and art restoration." },
  { atomicNumber:80, symbol:"Hg", name:"Mercury",       atomicMass:200.59,  category:"transition-metal",group:12, period:6, electronegativity:2.00, electronConfiguration:"[Xe] 4f¹⁴ 5d¹⁰ 6s²",oxidationStates:[1,2],     meltingPoint:234.32, boilingPoint:629.88, discoveryYear:null, discoveredBy:null,              phase:"liquid", radioactive:false, shells:[2,8,18,32,18,2],summary:"The only metal that is liquid at standard conditions. Used in thermometers, barometers, and fluorescent lights. Highly toxic; causes neurological damage. Named after the planet Mercury." },
  { atomicNumber:81, symbol:"Tl", name:"Thallium",      atomicMass:204.383, category:"post-transition", group:13, period:6, electronegativity:1.62, electronConfiguration:"[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹",oxidationStates:[1,3],  meltingPoint:577,    boilingPoint:1746,   discoveryYear:1861, discoveredBy:"William Crookes",  phase:"solid", radioactive:false, shells:[2,8,18,32,18,3],summary:"Soft gray post-transition metal that is highly toxic. Used in infrared detectors and specialty glass. Historically used in rat poison before its toxicity was widely recognized." },
  { atomicNumber:82, symbol:"Pb", name:"Lead",          atomicMass:207.2,   category:"post-transition", group:14, period:6, electronegativity:2.33, electronConfiguration:"[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²",oxidationStates:[2,4],  meltingPoint:600.61, boilingPoint:2022,   discoveryYear:null, discoveredBy:null,              phase:"solid", radioactive:false, shells:[2,8,18,32,18,4],summary:"Heavy, soft, malleable metal with a long history of human use. Used in lead-acid batteries and radiation shielding. Historically used in pipes and paint, despite being highly toxic." },
  { atomicNumber:83, symbol:"Bi", name:"Bismuth",       atomicMass:208.980, category:"post-transition", group:15, period:6, electronegativity:2.02, electronConfiguration:"[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³",oxidationStates:[3],    meltingPoint:544.7,  boilingPoint:1837,   discoveryYear:null, discoveredBy:null,              phase:"solid", radioactive:false, shells:[2,8,18,32,18,5],summary:"Pink-tinged diamagnetic metal and the heaviest stable element. Used in pharmaceuticals, fire extinguishing systems, and as a non-toxic replacement for lead in solders." },
  { atomicNumber:84, symbol:"Po", name:"Polonium",      atomicMass:209,     category:"metalloid",       group:16, period:6, electronegativity:2.00, electronConfiguration:"[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴",oxidationStates:[2,4],  meltingPoint:527,    boilingPoint:1235,   discoveryYear:1898, discoveredBy:"Marie Curie",     phase:"solid", radioactive:true,  shells:[2,8,18,32,18,6],summary:"Highly radioactive metalloid discovered by Marie and Pierre Curie. Used in anti-static devices and as a neutron source. Po-210 was famously used to poison Alexander Litvinenko." },
  { atomicNumber:85, symbol:"At", name:"Astatine",      atomicMass:210,     category:"halogen",         group:17, period:6, electronegativity:2.20, electronConfiguration:"[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵",oxidationStates:[-1,1,3,5],meltingPoint:575,  boilingPoint:610,    discoveryYear:1940, discoveredBy:"Dale R. Corson",  phase:"solid", radioactive:true,  shells:[2,8,18,32,18,7],summary:"Rarest naturally occurring element on Earth with no stable isotopes. Most stable isotope At-211 has a half-life of only 7 hours. Being explored for targeted alpha therapy in cancer treatment." },
  { atomicNumber:86, symbol:"Rn", name:"Radon",         atomicMass:222,     category:"noble-gas",       group:18, period:6, electronegativity:null, electronConfiguration:"[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶",oxidationStates:[0],    meltingPoint:202,    boilingPoint:211.5,  discoveryYear:1900, discoveredBy:"Friedrich Ernst Dorn", phase:"gas",  radioactive:true,  shells:[2,8,18,32,18,8],summary:"Colorless radioactive noble gas produced by the decay of radium. A significant health hazard — it is the second leading cause of lung cancer after smoking when it accumulates in buildings." },
  { atomicNumber:87, symbol:"Fr", name:"Francium",      atomicMass:223,     category:"alkali-metal",    group:1,  period:7, electronegativity:0.70, electronConfiguration:"[Rn] 7s¹",         oxidationStates:[1],       meltingPoint:281,    boilingPoint:950,    discoveryYear:1939, discoveredBy:"Marguerite Perey", phase:"solid", radioactive:true,  shells:[2,8,18,32,18,8,1],summary:"Highly radioactive alkali metal and the second rarest naturally occurring element. Most unstable of the first 101 elements; only a few grams exist in Earth's crust at any time." },
  { atomicNumber:88, symbol:"Ra", name:"Radium",        atomicMass:226,     category:"alkaline-earth",  group:2,  period:7, electronegativity:0.90, electronConfiguration:"[Rn] 7s²",         oxidationStates:[2],       meltingPoint:1233,   boilingPoint:2010,   discoveryYear:1898, discoveredBy:"Marie Curie",     phase:"solid", radioactive:true,  shells:[2,8,18,32,18,8,2],summary:"Radioactive alkaline earth metal discovered by Marie and Pierre Curie. Formerly used in luminous paints (Radium Girls scandal) and cancer treatment; now largely replaced by safer alternatives." },
  { atomicNumber:89, symbol:"Ac", name:"Actinium",      atomicMass:227,     category:"actinide",        group:null,period:7, electronegativity:1.10, electronConfiguration:"[Rn] 6d¹ 7s²",     oxidationStates:[3],       meltingPoint:1323,   boilingPoint:3471,   discoveryYear:1899, discoveredBy:"André-Louis Debierne", phase:"solid", radioactive:true,  shells:[2,8,18,32,18,9,2],summary:"Silvery radioactive metal that glows blue in the dark due to its intense radioactivity. Prototype for the actinide series; used as a neutron source and in experimental cancer treatment." },
  { atomicNumber:90, symbol:"Th", name:"Thorium",       atomicMass:232.038, category:"actinide",        group:null,period:7, electronegativity:1.30, electronConfiguration:"[Rn] 6d² 7s²",     oxidationStates:[4],       meltingPoint:2115,   boilingPoint:5061,   discoveryYear:1829, discoveredBy:"Jöns Jacob Berzelius", phase:"solid", radioactive:true,  shells:[2,8,18,32,18,10,2],summary:"Radioactive actinide more abundant than uranium in Earth's crust. Proposed as a nuclear fuel due to its high energy density and ability to breed uranium-233 in a thorium fuel cycle." },
  { atomicNumber:91, symbol:"Pa", name:"Protactinium",  atomicMass:231.036, category:"actinide",        group:null,period:7, electronegativity:1.50, electronConfiguration:"[Rn] 5f² 6d¹ 7s²", oxidationStates:[4,5],     meltingPoint:1841,   boilingPoint:4300,   discoveryYear:1913, discoveredBy:"Kasimir Fajans",  phase:"solid", radioactive:true,  shells:[2,8,18,32,20,9,2],summary:"Dense silvery-gray radioactive actinide with few commercial applications due to its rarity and toxicity. Intermediate in the decay chain of uranium-235." },
  { atomicNumber:92, symbol:"U",  name:"Uranium",       atomicMass:238.029, category:"actinide",        group:null,period:7, electronegativity:1.38, electronConfiguration:"[Rn] 5f³ 6d¹ 7s²", oxidationStates:[3,4,5,6], meltingPoint:1405.3, boilingPoint:4404,   discoveryYear:1789, discoveredBy:"Martin Heinrich Klaproth", phase:"solid", radioactive:true,  shells:[2,8,18,32,21,9,2],summary:"Weakly radioactive actinide and the most important nuclear fuel. U-235 undergoes fission in nuclear reactors and weapons. Depleted uranium is used in armor-piercing ammunition and counterweights." },
  { atomicNumber:93, symbol:"Np", name:"Neptunium",     atomicMass:237,     category:"actinide",        group:null,period:7, electronegativity:1.36, electronConfiguration:"[Rn] 5f⁴ 6d¹ 7s²", oxidationStates:[3,4,5,6,7],meltingPoint:917,   boilingPoint:4273,   discoveryYear:1940, discoveredBy:"Edwin McMillan",  phase:"solid", radioactive:true,  shells:[2,8,18,32,22,9,2],summary:"First transuranic element to be synthesized. Produced in small amounts in nuclear reactors as a byproduct of uranium irradiation. Used in neutron detection instruments." },
  { atomicNumber:94, symbol:"Pu", name:"Plutonium",     atomicMass:244,     category:"actinide",        group:null,period:7, electronegativity:1.28, electronConfiguration:"[Rn] 5f⁶ 7s²",     oxidationStates:[3,4,5,6], meltingPoint:912.5,  boilingPoint:3501,   discoveryYear:1940, discoveredBy:"Glenn T. Seaborg", phase:"solid", radioactive:true,  shells:[2,8,18,32,24,8,2],summary:"Radioactive transuranic actinide used in nuclear weapons and nuclear power generation. Extremely toxic metal; one of the most dangerous substances known due to its radioactivity and chemical toxicity." },
  { atomicNumber:95, symbol:"Am", name:"Americium",     atomicMass:243,     category:"actinide",        group:null,period:7, electronegativity:1.30, electronConfiguration:"[Rn] 5f⁷ 7s²",     oxidationStates:[3,4,5,6], meltingPoint:1449,   boilingPoint:2880,   discoveryYear:1944, discoveredBy:"Glenn T. Seaborg", phase:"solid", radioactive:true,  shells:[2,8,18,32,25,8,2],summary:"Radioactive transuranic actinide. Am-241 is used in household smoke detectors as an ionization source. Named after the Americas, just as europium was named after Europe." },
  { atomicNumber:96, symbol:"Cm", name:"Curium",        atomicMass:247,     category:"actinide",        group:null,period:7, electronegativity:1.30, electronConfiguration:"[Rn] 5f⁷ 6d¹ 7s²", oxidationStates:[3],       meltingPoint:1613,   boilingPoint:3383,   discoveryYear:1944, discoveredBy:"Glenn T. Seaborg", phase:"solid", radioactive:true,  shells:[2,8,18,32,25,9,2],summary:"Synthetic radioactive actinide named after Marie and Pierre Curie. Used as a power source in spacecraft (Curium-242) and as an alpha source for X-ray spectrometers on Mars rovers." },
  { atomicNumber:97, symbol:"Bk", name:"Berkelium",     atomicMass:247,     category:"actinide",        group:null,period:7, electronegativity:1.30, electronConfiguration:"[Rn] 5f⁹ 7s²",     oxidationStates:[3,4],     meltingPoint:1259,   boilingPoint:null,   discoveryYear:1949, discoveredBy:"Glenn T. Seaborg", phase:"solid", radioactive:true,  shells:[2,8,18,32,27,8,2],summary:"Synthetic radioactive actinide named after Berkeley, California. Primarily used as a target material for synthesizing heavier transuranic elements such as tennessine." },
  { atomicNumber:98, symbol:"Cf", name:"Californium",   atomicMass:251,     category:"actinide",        group:null,period:7, electronegativity:1.30, electronConfiguration:"[Rn] 5f¹⁰ 7s²",    oxidationStates:[3],       meltingPoint:1173,   boilingPoint:null,   discoveryYear:1950, discoveredBy:"Glenn T. Seaborg", phase:"solid", radioactive:true,  shells:[2,8,18,32,28,8,2],summary:"Synthetic radioactive actinide that is one of the few that can sustain a nuclear chain reaction. Used as a neutron source for starting nuclear reactors and in portable metal detectors at airports." },
  { atomicNumber:99, symbol:"Es", name:"Einsteinium",   atomicMass:252,     category:"actinide",        group:null,period:7, electronegativity:1.30, electronConfiguration:"[Rn] 5f¹¹ 7s²",    oxidationStates:[2,3],     meltingPoint:1133,   boilingPoint:null,   discoveryYear:1952, discoveredBy:"Albert Ghiorso",  phase:"solid", radioactive:true,  shells:[2,8,18,32,29,8,2],summary:"Synthetic radioactive actinide discovered in fallout from the first thermonuclear bomb test. Named after Albert Einstein. Has no significant practical applications due to its extreme rarity." },
  { atomicNumber:100,symbol:"Fm", name:"Fermium",       atomicMass:257,     category:"actinide",        group:null,period:7, electronegativity:1.30, electronConfiguration:"[Rn] 5f¹² 7s²",    oxidationStates:[2,3],     meltingPoint:1800,   boilingPoint:null,   discoveryYear:1952, discoveredBy:"Albert Ghiorso",  phase:"solid", radioactive:true,  shells:[2,8,18,32,30,8,2],summary:"Synthetic radioactive actinide named after Enrico Fermi. Produced in nuclear reactors through multiple neutron captures. Too scarce for practical applications beyond research." },
  { atomicNumber:101,symbol:"Md", name:"Mendelevium",   atomicMass:258,     category:"actinide",        group:null,period:7, electronegativity:1.30, electronConfiguration:"[Rn] 5f¹³ 7s²",    oxidationStates:[2,3],     meltingPoint:1100,   boilingPoint:null,   discoveryYear:1955, discoveredBy:"Albert Ghiorso",  phase:"solid", radioactive:true,  shells:[2,8,18,32,31,8,2],summary:"Synthetic radioactive actinide named after Dmitri Mendeleev. First element produced one atom at a time. Only produced in tiny quantities with no practical applications beyond fundamental research." },
  { atomicNumber:102,symbol:"No", name:"Nobelium",      atomicMass:259,     category:"actinide",        group:null,period:7, electronegativity:1.30, electronConfiguration:"[Rn] 5f¹⁴ 7s²",    oxidationStates:[2,3],     meltingPoint:1100,   boilingPoint:null,   discoveryYear:1958, discoveredBy:"Albert Ghiorso",  phase:"solid", radioactive:true,  shells:[2,8,18,32,32,8,2],summary:"Synthetic radioactive actinide named after Alfred Nobel. Unlike other actinides, most stable oxidation state in solution is +2. Only produced in microscopic amounts in particle accelerators." },
  { atomicNumber:103,symbol:"Lr", name:"Lawrencium",    atomicMass:262,     category:"actinide",        group:null,period:7, electronegativity:1.30, electronConfiguration:"[Rn] 5f¹⁴ 7s² 7p¹", oxidationStates:[3],       meltingPoint:1900,   boilingPoint:null,   discoveryYear:1961, discoveredBy:"Albert Ghiorso",  phase:"solid", radioactive:true,  shells:[2,8,18,32,32,8,3],summary:"Synthetic radioactive actinide and last member of the actinide series. Named after Ernest Lawrence, inventor of the cyclotron. Most stable isotope Lr-266 has a half-life of about 11 hours." },
  { atomicNumber:104,symbol:"Rf", name:"Rutherfordium", atomicMass:267,     category:"transition-metal",group:4,  period:7, electronegativity:null, electronConfiguration:"[Rn] 5f¹⁴ 6d² 7s²", oxidationStates:[4],       meltingPoint:null,   boilingPoint:null,   discoveryYear:1969, discoveredBy:"Albert Ghiorso",  phase:"unknown", radioactive:true, shells:[2,8,18,32,32,10,2],summary:"First transactinide element. Named after Ernest Rutherford. Chemical properties are similar to hafnium as predicted by periodic trends. Only a few atoms have been created." },
  { atomicNumber:105,symbol:"Db", name:"Dubnium",       atomicMass:268,     category:"transition-metal",group:5,  period:7, electronegativity:null, electronConfiguration:"[Rn] 5f¹⁴ 6d³ 7s²", oxidationStates:[5],       meltingPoint:null,   boilingPoint:null,   discoveryYear:1970, discoveredBy:"Albert Ghiorso",  phase:"unknown", radioactive:true, shells:[2,8,18,32,32,11,2],summary:"Synthetic transactinide element named after Dubna, Russia. Expected to behave chemically like niobium and tantalum. Only a few atoms have ever been created in particle accelerators." },
  { atomicNumber:106,symbol:"Sg", name:"Seaborgium",    atomicMass:271,     category:"transition-metal",group:6,  period:7, electronegativity:null, electronConfiguration:"[Rn] 5f¹⁴ 6d⁴ 7s²", oxidationStates:[6],       meltingPoint:null,   boilingPoint:null,   discoveryYear:1974, discoveredBy:"Albert Ghiorso",  phase:"unknown", radioactive:true, shells:[2,8,18,32,32,12,2],summary:"Synthetic superheavy transactinide named after Glenn T. Seaborg. Chemical properties analogous to tungsten. Longest-lived isotope has a half-life of about 14 minutes." },
  { atomicNumber:107,symbol:"Bh", name:"Bohrium",       atomicMass:270,     category:"transition-metal",group:7,  period:7, electronegativity:null, electronConfiguration:"[Rn] 5f¹⁴ 6d⁵ 7s²", oxidationStates:[7],       meltingPoint:null,   boilingPoint:null,   discoveryYear:1981, discoveredBy:"Peter Armbruster", phase:"unknown", radioactive:true, shells:[2,8,18,32,32,13,2],summary:"Synthetic superheavy transactinide element named after Niels Bohr. Expected to behave similarly to rhenium. Only about 100 atoms have ever been produced." },
  { atomicNumber:108,symbol:"Hs", name:"Hassium",       atomicMass:277,     category:"transition-metal",group:8,  period:7, electronegativity:null, electronConfiguration:"[Rn] 5f¹⁴ 6d⁶ 7s²", oxidationStates:[8],       meltingPoint:null,   boilingPoint:null,   discoveryYear:1984, discoveredBy:"Peter Armbruster", phase:"unknown", radioactive:true, shells:[2,8,18,32,32,14,2],summary:"Synthetic superheavy element named after the German state of Hesse. Expected to be the densest of all elements. Hassium oxide is volatile like osmium tetroxide." },
  { atomicNumber:109,symbol:"Mt", name:"Meitnerium",    atomicMass:278,     category:"unknown",         group:9,  period:7, electronegativity:null, electronConfiguration:"[Rn] 5f¹⁴ 6d⁷ 7s²", oxidationStates:[3,6],     meltingPoint:null,   boilingPoint:null,   discoveryYear:1982, discoveredBy:"Peter Armbruster", phase:"unknown", radioactive:true, shells:[2,8,18,32,32,15,2],summary:"Synthetic superheavy element named after physicist Lise Meitner, one of the discoverers of nuclear fission. Too short-lived for practical applications." },
  { atomicNumber:110,symbol:"Ds", name:"Darmstadtium",  atomicMass:281,     category:"unknown",         group:10, period:7, electronegativity:null, electronConfiguration:"[Rn] 5f¹⁴ 6d⁸ 7s²", oxidationStates:[0,2,4,6], meltingPoint:null,   boilingPoint:null,   discoveryYear:1994, discoveredBy:"Peter Armbruster", phase:"unknown", radioactive:true, shells:[2,8,18,32,32,16,2],summary:"Synthetic superheavy element named after Darmstadt, Germany, where it was discovered. Expected to be a noble metal similar to platinum. Only a few atoms have been created." },
  { atomicNumber:111,symbol:"Rg", name:"Roentgenium",   atomicMass:282,     category:"unknown",         group:11, period:7, electronegativity:null, electronConfiguration:"[Rn] 5f¹⁴ 6d¹⁰ 7s¹", oxidationStates:[1,3,5],   meltingPoint:null,   boilingPoint:null,   discoveryYear:1994, discoveredBy:"Peter Armbruster", phase:"unknown", radioactive:true, shells:[2,8,18,32,32,18,1],summary:"Synthetic superheavy element named after Wilhelm Röntgen, discoverer of X-rays. Relativistic effects may give it unusual chemical properties distinct from those of gold." },
  { atomicNumber:112,symbol:"Cn", name:"Copernicium",   atomicMass:285,     category:"transition-metal",group:12, period:7, electronegativity:null, electronConfiguration:"[Rn] 5f¹⁴ 6d¹⁰ 7s²", oxidationStates:[0,2],     meltingPoint:null,   boilingPoint:null,   discoveryYear:1996, discoveredBy:"Peter Armbruster", phase:"unknown", radioactive:true, shells:[2,8,18,32,32,18,2],summary:"Synthetic superheavy element named after Nicolaus Copernicus. Predicted to be a gas at room temperature due to extreme relativistic effects, potentially behaving more like a noble gas than a metal." },
  { atomicNumber:113,symbol:"Nh", name:"Nihonium",      atomicMass:286,     category:"post-transition", group:13, period:7, electronegativity:null, electronConfiguration:"[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹",oxidationStates:[1,3],  meltingPoint:null,   boilingPoint:null,   discoveryYear:2004, discoveredBy:"Kosuke Morita",   phase:"unknown", radioactive:true, shells:[2,8,18,32,32,18,3],summary:"Synthetic superheavy element named after Japan (Nihon in Japanese). First element discovered in Asia. Only a few atoms have ever been created with a very short half-life of ~20 seconds." },
  { atomicNumber:114,symbol:"Fl", name:"Flerovium",     atomicMass:289,     category:"post-transition", group:14, period:7, electronegativity:null, electronConfiguration:"[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²",oxidationStates:[2,4],  meltingPoint:null,   boilingPoint:null,   discoveryYear:1999, discoveredBy:"Yuri Oganessian", phase:"unknown", radioactive:true, shells:[2,8,18,32,32,18,4],summary:"Synthetic superheavy element named after the Flerov Laboratory of Nuclear Reactions. Predicted to be a noble-gas-like element due to extreme relativistic effects despite being in group 14." },
  { atomicNumber:115,symbol:"Mc", name:"Moscovium",     atomicMass:290,     category:"post-transition", group:15, period:7, electronegativity:null, electronConfiguration:"[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³",oxidationStates:[1,3],  meltingPoint:null,   boilingPoint:null,   discoveryYear:2003, discoveredBy:"Yuri Oganessian", phase:"unknown", radioactive:true, shells:[2,8,18,32,32,18,5],summary:"Synthetic superheavy element named after Moscow Oblast in Russia. Expected to have properties similar to bismuth. Extremely short-lived with half-lives under a second." },
  { atomicNumber:116,symbol:"Lv", name:"Livermorium",   atomicMass:293,     category:"post-transition", group:16, period:7, electronegativity:null, electronConfiguration:"[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴",oxidationStates:[2,4],  meltingPoint:null,   boilingPoint:null,   discoveryYear:2000, discoveredBy:"Yuri Oganessian", phase:"unknown", radioactive:true, shells:[2,8,18,32,32,18,6],summary:"Synthetic superheavy element named after Lawrence Livermore National Laboratory. Expected to be a liquid metal at room temperature with properties similar to polonium." },
  { atomicNumber:117,symbol:"Ts", name:"Tennessine",    atomicMass:294,     category:"halogen",         group:17, period:7, electronegativity:null, electronConfiguration:"[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵",oxidationStates:[-1,1,3,5], meltingPoint:null, boilingPoint:null,   discoveryYear:2010, discoveredBy:"Yuri Oganessian", phase:"unknown", radioactive:true, shells:[2,8,18,32,32,18,7],summary:"Synthetic superheavy element named after Tennessee. Among the most recently discovered elements. Expected to have properties of a post-transition metal rather than a typical halogen." },
  { atomicNumber:118,symbol:"Og", name:"Oganesson",     atomicMass:294,     category:"noble-gas",       group:18, period:7, electronegativity:null, electronConfiguration:"[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶",oxidationStates:[0,2,4,6], meltingPoint:null, boilingPoint:null,   discoveryYear:2002, discoveredBy:"Yuri Oganessian", phase:"unknown", radioactive:true, shells:[2,8,18,32,32,18,8],summary:"Heaviest and most recently confirmed element, named after physicist Yuri Oganessian. Despite being in the noble gas group, predicted to be a solid at room temperature due to relativistic effects." },
];

export const ELEMENT_BY_SYMBOL: Record<string, ChemElement> = {};
export const ELEMENT_BY_NUMBER: Record<number, ChemElement> = {};
ELEMENTS.forEach(e => {
  ELEMENT_BY_SYMBOL[e.symbol] = e;
  ELEMENT_BY_NUMBER[e.atomicNumber] = e;
});

export const CATEGORY_COLORS: Record<ElementCategory, { bg: string; text: string; border: string }> = {
  "nonmetal":         { bg: "rgba(34,197,94,0.15)",    text: "#86efac", border: "rgba(34,197,94,0.4)" },
  "noble-gas":        { bg: "rgba(168,85,247,0.15)",   text: "#d8b4fe", border: "rgba(168,85,247,0.4)" },
  "alkali-metal":     { bg: "rgba(239,68,68,0.15)",    text: "#fca5a5", border: "rgba(239,68,68,0.4)" },
  "alkaline-earth":   { bg: "rgba(249,115,22,0.15)",   text: "#fdba74", border: "rgba(249,115,22,0.4)" },
  "transition-metal": { bg: "rgba(59,130,246,0.15)",   text: "#93c5fd", border: "rgba(59,130,246,0.4)" },
  "post-transition":  { bg: "rgba(6,182,212,0.15)",    text: "#67e8f9", border: "rgba(6,182,212,0.4)" },
  "metalloid":        { bg: "rgba(234,179,8,0.15)",    text: "#fde047", border: "rgba(234,179,8,0.4)" },
  "halogen":          { bg: "rgba(20,184,166,0.15)",   text: "#5eead4", border: "rgba(20,184,166,0.4)" },
  "lanthanide":       { bg: "rgba(236,72,153,0.15)",   text: "#f9a8d4", border: "rgba(236,72,153,0.4)" },
  "actinide":         { bg: "rgba(244,63,94,0.15)",    text: "#fda4af", border: "rgba(244,63,94,0.4)" },
  "unknown":          { bg: "rgba(100,116,139,0.15)",  text: "#94a3b8", border: "rgba(100,116,139,0.4)" },
};
